{"timestamp": "2024-03-03 13:57:34.137711", "exception": "user forced crash", "traceback": "Traceback (most recent call last):\n  File \"/home/adrian/Documents/GitHub/wdhs-alevel-flight-sim/OpenPyFlySim/flight_sim.py\", line 467, in main\n    raise Exception(\"user forced crash\")\nException: user forced crash\n", "variables": "[array([231.02701945,   3.19836359, 447.72252093]), array([278.575,  -1.135,   0.   ]), 14.084507042253522, 78301, [], [(array([232.        ,   0.53333333, 447.        ]), array([231.        ,   0.53333333, 447.        ]), array([231.        ,   0.53333333, 448.        ])), (array([232.        ,   0.53333333, 447.        ]), array([231.        ,   0.53333333, 448.        ]), array([232.        ,   0.53333333, 448.        ])), (array([232.        ,   0.53333333, 448.        ]), array([231.        ,   0.53333333, 448.        ]), array([231.        ,   0.53333333, 449.        ])), (array([232.        ,   0.53333333, 448.        ]), array([231.        ,   0.53333333, 449.        ]), array([232.        ,   0.53333333, 449.        ]))]]", "usertext": "TEST", "checksum": "e8f8f1ff70ebf0e461684da6e05e97b1", "systemDetails": ["Linux", "adrian", "6.5.0-21-generic", "#21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2", "x86_64"], "logchecksum": "ba5082fed180c887f91940f240ad28e2", "sent": 1}